// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  content: dynamic(() => import('./Content')),
  image_with_text: dynamic(() => import('./ImageWithText')),
  inspire: dynamic(() => import('./Inspire')),
}
